#define CAM_PIN_SDA   A4
#define CAM_PIN_SCL   A5
#define CAM_PIN_D0    2
#define CAM_PIN_D1    3
#define CAM_PIN_D2    4
#define CAM_PIN_D3    5
#define CAM_PIN_D4    6
#define CAM_PIN_D5    7
#define CAM_PIN_D6    8
#define CAM_PIN_D7    9
#define CAM_PIN_PCLK 10
#define CAM_PIN_VSNC 11
#define CAM_PIN_HREF 12
#define CAM_PIN_XCLK NULL
